// JScript 文件
/* var _menus ={
"basic":
 [
           {"id":"1",
           "parentid":-1",
           "text":"project",
           "attributes":{"url":""},
           "children":[
                          {"id":"101",
		                   "text":"default105",
		                   "children":[
		                              {"id":"10101",
			                           "text":"default10502",
			                           "children":[
			                                      {"id":"1010101","text":"default1050201.jl"},
					                              {"id":"1010102","text":"default1050202.jl"}
					                              ]
			                          },
			                          {"id":"10102",
			                           "text":"default10503",
			                           "children":[
			                                      {"id":"1010201","text":"default1050301.jl"}
					                              ]
			                          }
			                          ]
	                       },
		                  {"id":"102",
		                   "text":"project105",
		                   "children":[
		                              {"id":"10201",
			                           "text":"default10501",
			                           "children":[
			                                      {"id":"1020101","text":"default1050101.jl"},
					                              {"id":"1020102","text":"default1050102.jl"}
					                              ]
				                      }
				                      ]
		                  }
		            ]
	     }
 ]
}*/    
var _menus =
{"basic":[{"id":"1","parentid":"-1","text":"project","iconCls":"","attributes":{"url":""},"checked":"","isFolder":"","isLeaf":"","orderNum":"","children":[{"id":"101","text":"default105","children":[{"id":"10101","text":"default10502","children":[{"id":"1010101","text":"default1050201.jl","attributes":{"url":"ace-master/aceeditor_js.aspx"}},{"id":"1010102","text":"default1050202.jl","attributes":{"url":"ace-master/aceeditor_js.aspx"}}]},{"id":"10102","text":"default10503","children":[{"id":"1010201","text":"default1050301.jl","attributes":{"url":"ace-master/aceeditor_js.aspx"}}]},{"id":"10103","text":"default10103.jl","attributes":{"url":"ace-master/aceeditor_js.aspx"}},{"id":"10104","text":"default10104.jl","attributes":{"url":"ace-master/aceeditor_js.aspx"}}]},{"id":"102","text":"project105","children":[{"id":"10201","text":"default10501","children":[{"id":"1020101","text":"default1020103","children":[{"id":"102010101","text":"default102010301.jl","attributes":{"url":"ace-master/aceeditor_js.aspx"}},{"id":"102010102","text":"default102010302.jl","attributes":{"url":"ace-master/aceeditor_js.aspx"}}]},{"id":"1020102","text":"default1050101.jl","attributes":{"url":"ace-master/aceeditor_js.aspx"}},{"id":"1020103","text":"default1050102.jl","attributes":{"url":"ace-master/aceeditor_js.aspx"}}]}]}]}]}


/*{
   "basic":
  [
        {   "id":"1",
            "parentid":"-1",
            "text":"project",
            "iconCls":"",
            "attributes":{"url":""},
            "checked":"",
            "isFolder":"",
            "isLeaf":"",
            "orderNum":"",
            "children":[ {"id":"101",
		                   "text":"default105",
		                   "children":[
		                              {"id":"10101",
			                           "text":"default10502",
			                           "children":[
			                                      {"id":"1010101","text":"default1050201.jl"},
					                              {"id":"1010102","text":"default1050202.jl"}
					                              ]
			                          },
			                          {"id":"10102",
			                           "text":"default10503",
			                           "children":[
			                                      {"id":"1010201","text":"default1050301.jl"}
					                              ]
			                          }
			                          ]
	                       },
		                  {"id":"102",
		                   "text":"project105",
		                   "children":[
		                              {"id":"10201",
			                           "text":"default10501",
			                           "children":[
			                                      {"id":"1020101","text":"default1050101.jl"},
					                              {"id":"1020102","text":"default1050102.jl"}
					                              ]
				                      }
				                      ]
		                  }
	            ]
        }
    ]
}*/